### ISSUE TITLE
License

### ISSUE THREAD

**Issue by helgoboss** [audiocloud/reaper-chunks#4]
Hi! May I ask, what are the licensing terms of this library? I would like to potentially use it and maybe contribute.

**Comment by baadc0de** [comment]
Hi,

like the rest of audiocloud, it is meant to be MIT licensed. This project is not currently actively used in the version of audiocloud we are building right now, but that may change again as we progress to 1.0 release. PRs are more than welcome, though there may be some lag to actually test anything.

EDIT: license uploaded.

**Comment by helgoboss** [comment]
Thanks a lot! That clears is up.
